### ISSUE TITLE
MIUI13，授予截屏和录制视频权限后就闪退重启，然后再开始学习就显示无障碍服务出现故障

### ISSUE THREAD

**Issue by yangck1** [sec-an/Better-Auto-XXQG#39]

**Comment by yangck1** [comment]
Version: 614
Android: 31
android.os.RemoteException: Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)

java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=17777, result=-1, data=Intent { (has extras) }} to activity {org.autojs.autojs.dev/com.stardust.autojs.core.image.capture.ScreenCaptureRequestActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
android.app.ActivityThread.deliverResults(ActivityThread.java:5455)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)

**Comment by boy5260** [comment]
我的也出现了，我还是K50，没有老版本，郁闷啊

**Comment by sec-an** [comment]
自用MIUI13没有遇到类似情况…

**Comment by yangck1** [comment]
fix
